# fly.toml app configuration file generated for example-app-01 on 2024-08-18T13:11:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'example-app-01'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = "production"
  # APP_KEY = "base64:E3zPFQFnXmTAZ1hgXi/8JXUG+AegvzFEqIAcvG5uV6E=" to secret
  APP_DEBUG = "true"
  APP_URL = "https://example-app-01.fly.dev"
  APP_TIMEZONE = "UTC"
  
  LOG_CHANNEL = "stack"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  
  DB_CONNECTION = "pgsql"
  DB_HOST = "example-app-01-db.internal" # Fly.ioの内部DNS名
  DB_PORT = 5433
  DB_DATABASE = "laravel"
  # DB_USERNAME = "sail" DB_URを代わりに使うのでコメントアウト
  # DB_PASSWORD = "password" DB_URを代わりに使うのでコメントアウト

  SESSION_DRIVER = "database"
  SESSION_LIFETIME = "120"
  SESSION_SECURE_COOKIE = "true"
  
  QUEUE_CONNECTION = "database"
  CACHE_STORE = "database"

  REDIS_CLIENT = "phpredis"
  REDIS_HOST = "redis.internal"
  # REDIS_PASSWORD = "null" to secret
  REDIS_PORT = "6379"
  CACHE_DRIVER= "redis"

  MAIL_MAILER = "smtp"
  MAIL_HOST = "mailpit.internal"
  MAIL_PORT = "1025"
  MAIL_FROM_ADDRESS = "hello@example.com"
  MAIL_FROM_NAME = "Laravel"

  SCOUT_DRIVER = "meilisearch"
  MEILISEARCH_HOST = "http://meilisearch.internal:7700"
  MEILISEARCH_NO_ANALYTICS = "false"
  
  APP_PORT = "80"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = 'shared-cpu-2x'

[mounts]
  source = "pgsql_data"
  destination = "/var/www/html" #/var/lib/postgresql/data