app = 'example-app-young-flower-4714'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_SECURE_COOKIE = 'true'
  APP_URL=https://example-app-young-flower-4714.fly.dev
  APP_KEY=base64:E3zPFQFnXmTAZ1hgXi/8JXUG+AegvzFEqIAcvG5uV6E=
  APP_TIMEZONE=UTC
  APP_FALLBACK_LOCALE=en
  APP_FAKER_LOCALE=en_US
  LOG_CHANNEL=stack
  LOG_STACK=single
  LOG_DEPRECATIONS_CHANNEL=null
  LOG_LEVEL=debug
  DB_CONNECTION=pgsql
  DB_HOST=example-app-young-flower-4714-db.flycast
  DB_PORT=5432
  SESSION_DRIVER=redis
  SESSION_LIFETIME=120
  SESSION_ENCRYPT=false
  SESSION_PATH=/
  SESSION_DOMAIN=null
  BROADCAST_CONNECTION=log
  FILESYSTEM_DISK=local
  QUEUE_CONNECTION=database
  CACHE_STORE=redis
  CACHE_PREFIX=
  MEMCACHED_HOST=127.0.0.1
  REDIS_CLIENT=phpredis
  REDIS_HOST=redis
  REDIS_PASSWORD=null
  REDIS_PORT=6379
  MAIL_MAILER=smtp
  MAIL_HOST=mailpit
  MAIL_PORT=1025
  MAIL_USERNAME=null
  MAIL_PASSWORD=null
  MAIL_ENCRYPTION=null
  MAIL_FROM_ADDRESS="hello@example.com"
  MAIL_FROM_NAME="laravel"
  VITE_APP_NAME="laravel"
  SCOUT_DRIVER=meilisearch
  MEILISEARCH_HOST=http://meilisearch:7700
  MEILISEARCH_NO_ANALYTICS=false
  APP_PORT=80

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  protocol = "tcp"
  [[http_service.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  size = 'shared-cpu-1x'